### ISSUE TITLE
[Enhancement] Support for Crystal 1.0

### ISSUE THREAD

**Issue by syeopite** [philnash/crotp#12]

**Comment by philnash** [comment]
The tests run successfully on Crystal 1.0. Do I need to update the shards.yml to declare 1.0 support?

**Comment by syeopite** [comment]
Yes, otherwise the `--ignore-crystal-version` parameter is required when using crotp which isn't an ideal solution.

**Comment by philnash** [comment]
Ah, of course. I remember that's what the tests run with 😄 

I'll get that updated and release a new version.

**Comment by syeopite** [comment]
👍 Thank you!

**Comment by philnash** [comment]
This is frustrating, but the base32 shard does not agree with the versions and you likely still won't be able to run without `--ignore-crystal-version`. 

I will reach out to the maintainer of base32 to see if they can release a similar upgrade to support Crystal 1.0.0. Otherwise I may have to fork the base32 implementation myself (that happened once before in an upgrade).

**Comment by philnash** [comment]
I've opened https://github.com/repomaa/base32/pull/1. Either it is accepted soon, or I will point the CrOTP  dependency to my fork and we should be good to carry on.

**Comment by syeopite** [comment]
I'll suggest also merging this PR from upstream noumar/base32#5 into your fork if the maintainer doesn't respond. It improves speed by quite a bit.

**Comment by philnash** [comment]
After waiting for PRs to be accepted to the other base32 forks, I eventually pointed this shard's dependency to my fork and released version 1.0.0 which supports Crystal 1.0.0.

Let me know if it is working for you.

**Comment by syeopite** [comment]
Looks good to me. Thank you so much for maintaining crotp!
