### ISSUE TITLE
Great project!

### ISSUE THREAD

**Issue by kingsleyh** [philnash/crotp#5]
Hi

I was really looking for something like this a few months ago but didn't find anything - great project. I just found this after I released my own TOTP shard here:  https://github.com/SushiChain/crystal-two-factor-auth

Your version looks very much like you took inspiration from the Ruby ROTP project :) - Mine only implements TOTP. 

we are using it on our SushiChain blockchain project: https://sushichain.io

**Comment by philnash** [comment]
Hi!

Thanks for the kind note! I did take inspiration from both ROTP and [notp](https://github.com/guyht/notp), thought the object oriented method felt more natural in Crystal which is why it came out closer to ROTP.

I'm excited you're using it. Let me know if there's anything else you need from it. I did most of the work a while back, but I just got the inspiration to come back and start checking off items from the to do list.

Cheers!
